# Generated by Django 5.1 on 2026-04-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuahang', '0002_nguoidung_avatar_nguoidung_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='gioi_tinh',
            field=models.CharField(choices=[('nam', 'Nam'), ('nu', 'Nữ'), ('unisex', 'Unisex')], default='unisex', max_length=20),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='kich_co',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='mau_sac',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
