# Generated by Django 5.1 on 2026-04-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuahang', '0003_sanpham_gioi_tinh_sanpham_kich_co_sanpham_mau_sac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoidung',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/macdinh.png', null=True, upload_to='avatars/'),
        ),
    ]
