# Generated by Django 5.1 on 2026-04-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuahang', '0004_alter_nguoidung_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoidung',
            name='hang_thanh_vien',
            field=models.CharField(choices=[('dong', 'Đồng'), ('bac', 'Bạc'), ('vang', 'Vàng'), ('bachkim', 'Bạch Kim'), ('kimcuong', 'Kim Cương')], default='dong', max_length=20),
        ),
    ]
