# Generated by Django 5.1 on 2026-04-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuahang', '0006_diachigiaohang'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='dia_chi_giao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donhang',
            name='ho_ten_nhan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='donhang',
            name='so_dien_thoai_nhan',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
