# Generated by Django 5.1 on 2026-04-28 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuahang', '0007_donhang_dia_chi_giao_donhang_ho_ten_nhan_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiaChiGiaoHang',
        ),
    ]
