# Generated by Django 5.1 on 2026-04-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuahang', '0008_delete_diachigiaohang'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanpham',
            options={'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AddField(
            model_name='sanpham',
            name='chat_lieu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='chieu_dai_ao',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='chieu_dai_quan',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='chieu_dai_tay',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='co_ao',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='loai_phu_kien',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='loai_quan',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='loai_san_pham',
            field=models.CharField(choices=[('ao', 'Áo'), ('quan', 'Quần'), ('phu_kien', 'Phụ kiện')], default='ao', max_length=20),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='trang_thai_kho',
            field=models.CharField(choices=[('con_hang', 'Còn hàng'), ('het_hang', 'Hết hàng'), ('sap_ve', 'Sắp về')], default='con_hang', max_length=20),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='xuat_xu',
            field=models.CharField(default='Việt Nam', max_length=100),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='kich_co',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='phong_cach',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
