# Generated by Django 5.1 on 2026-04-28 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuahang', '0009_alter_sanpham_options_sanpham_chat_lieu_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanpham',
            options={},
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='chieu_dai_ao',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='chieu_dai_quan',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='chieu_dai_tay',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='co_ao',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='gia',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='kich_co',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='loai_phu_kien',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='loai_quan',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='mau_sac',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='so_luong',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='trang_thai_kho',
        ),
        migrations.CreateModel(
            name='SanPhamBienThe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mau_sac', models.CharField(max_length=50)),
                ('kich_co', models.CharField(max_length=20)),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('so_luong', models.IntegerField(default=10)),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bien_the', to='cuahang.sanpham')),
            ],
            options={
                'verbose_name': 'Biến thể sản phẩm',
                'verbose_name_plural': 'Biến thể sản phẩm',
                'unique_together': {('san_pham', 'mau_sac', 'kich_co')},
            },
        ),
    ]
