# Generated by Django 5.1 on 2026-04-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuahang', '0010_alter_sanpham_options_remove_sanpham_chieu_dai_ao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanphambienthe',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='sanpham/bienthe/'),
        ),
    ]
