# Generated by Django 5.1 on 2026-05-02 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuahang', '0011_sanphambienthe_hinh_anh'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhGiaSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_sao', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('noi_dung', models.TextField()),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='reviews/')),
                ('ngay_danh_gia', models.DateTimeField(auto_now_add=True)),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia', to='cuahang.sanpham')),
            ],
            options={
                'verbose_name': 'Đánh giá sản phẩm',
                'ordering': ['-ngay_danh_gia'],
            },
        ),
        migrations.CreateModel(
            name='BangSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kich_co', models.CharField(max_length=20)),
                ('nguc', models.CharField(blank=True, max_length=50)),
                ('eo', models.CharField(blank=True, max_length=50)),
                ('mong', models.CharField(blank=True, max_length=50)),
                ('dai_ao', models.CharField(blank=True, max_length=50)),
                ('dai_quan', models.CharField(blank=True, max_length=50)),
                ('mo_ta', models.CharField(blank=True, max_length=100)),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bang_size', to='cuahang.sanpham')),
            ],
            options={
                'verbose_name': 'Bảng size',
                'unique_together': {('san_pham', 'kich_co')},
            },
        ),
    ]
