# Generated by Django 5.1 on 2026-05-02 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuahang', '0012_danhgiasanpham_bangsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='giohang',
            name='bien_the',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuahang.sanphambienthe'),
        ),
        migrations.AlterUniqueTogether(
            name='giohang',
            unique_together={('nguoi_dung', 'bien_the')},
        ),
    ]
