# Generated by Django 5.1 on 2026-05-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuahang', '0013_giohang_bien_the_alter_giohang_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bangsize',
            options={'verbose_name': 'Bảng Size', 'verbose_name_plural': 'Bảng Size'},
        ),
        migrations.RemoveField(
            model_name='bangsize',
            name='dai_ao',
        ),
        migrations.RemoveField(
            model_name='bangsize',
            name='dai_quan',
        ),
        migrations.RemoveField(
            model_name='bangsize',
            name='eo',
        ),
        migrations.RemoveField(
            model_name='bangsize',
            name='mong',
        ),
        migrations.RemoveField(
            model_name='bangsize',
            name='nguc',
        ),
        migrations.AddField(
            model_name='bangsize',
            name='can_nang_den',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cân nặng đến (kg)'),
        ),
        migrations.AddField(
            model_name='bangsize',
            name='can_nang_tu',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cân nặng từ (kg)'),
        ),
        migrations.AddField(
            model_name='bangsize',
            name='chieu_cao_den',
            field=models.CharField(blank=True, max_length=20, verbose_name='Chiều cao đến (cm)'),
        ),
        migrations.AddField(
            model_name='bangsize',
            name='chieu_cao_tu',
            field=models.CharField(blank=True, max_length=20, verbose_name='Chiều cao từ (cm)'),
        ),
        migrations.AddField(
            model_name='bangsize',
            name='chieu_dai_ao',
            field=models.CharField(blank=True, max_length=50, verbose_name='Chiều dài áo (cm)'),
        ),
        migrations.AddField(
            model_name='bangsize',
            name='chieu_dai_quan',
            field=models.CharField(blank=True, max_length=50, verbose_name='Chiều dài quần (cm)'),
        ),
        migrations.AddField(
            model_name='bangsize',
            name='chieu_dai_tay',
            field=models.CharField(blank=True, max_length=50, verbose_name='Chiều dài tay áo (cm)'),
        ),
        migrations.AddField(
            model_name='bangsize',
            name='chieu_rong',
            field=models.CharField(blank=True, max_length=50, verbose_name='Chiều rộng ngực (cm)'),
        ),
        migrations.AddField(
            model_name='bangsize',
            name='mo_ta_kich_co',
            field=models.TextField(blank=True, verbose_name='Mô tả kích cỡ phụ kiện'),
        ),
        migrations.AddField(
            model_name='bangsize',
            name='vong_eo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Vòng eo (cm)'),
        ),
        migrations.AlterField(
            model_name='bangsize',
            name='kich_co',
            field=models.CharField(max_length=20, verbose_name='Size (Quốc Tế)'),
        ),
        migrations.AlterField(
            model_name='bangsize',
            name='mo_ta',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ghi chú thêm'),
        ),
    ]
