# Generated by Django 5.1 on 2026-05-21 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuahang', '0014_alter_bangsize_options_remove_bangsize_dai_ao_and_more'),
    ]

    operations = [
    ]
