# Generated by Django 5.1 on 2026-05-21 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuahang', '0015_auto_20260521_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='khuyenmai',
            name='ap_dung_cho_hang',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='khuyenmai',
            name='da_su_dung',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='khuyenmai',
            name='gia_tri',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='khuyenmai',
            name='loai_giam',
            field=models.CharField(choices=[('phan_tram', 'Giảm phần trăm'), ('tien', 'Giảm số tiền'), ('freeship', 'Miễn phí vận chuyển')], default='phan_tram', max_length=20),
        ),
        migrations.AddField(
            model_name='khuyenmai',
            name='mo_ta',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='khuyenmai',
            name='so_luong',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='khuyenmai',
            name='ten_khuyen_mai',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='khuyenmai',
            name='phan_tram_giam',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserKhuyenMai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('da_su_dung', models.BooleanField(default=False)),
                ('ngay_nhan', models.DateTimeField(auto_now_add=True)),
                ('ngay_su_dung', models.DateTimeField(blank=True, null=True)),
                ('khuyen_mai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuahang.khuyenmai')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khuyen_mai_cua_toi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('nguoi_dung', 'khuyen_mai')},
            },
        ),
    ]
