# Generated by Django 5.1 on 2026-05-22 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuahang', '0016_khuyenmai_ap_dung_cho_hang_khuyenmai_da_su_dung_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userkhuyenmai',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='khuyenmai',
            name='ap_dung_cho_hang',
        ),
        migrations.RemoveField(
            model_name='khuyenmai',
            name='da_su_dung',
        ),
        migrations.RemoveField(
            model_name='khuyenmai',
            name='phan_tram_giam',
        ),
        migrations.RemoveField(
            model_name='khuyenmai',
            name='so_luong',
        ),
        migrations.AlterField(
            model_name='khuyenmai',
            name='gia_tri',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='khuyenmai',
            name='loai_giam',
            field=models.CharField(choices=[('phan_tram', 'Giảm phần trăm'), ('tien', 'Giảm số tiền'), ('freeship', 'Freeship')], max_length=20),
        ),
        migrations.AlterField(
            model_name='khuyenmai',
            name='mo_ta',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='khuyenmai',
            name='ten_khuyen_mai',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userkhuyenmai',
            name='nguoi_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_vouchers', to=settings.AUTH_USER_MODEL),
        ),
    ]
