# Generated by Django 5.1 on 2026-05-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuahang', '0017_alter_userkhuyenmai_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='khuyenmai',
            name='doi_tuong',
            field=models.CharField(choices=[('all', 'Tất cả thành viên'), ('bac', 'Bạc trở lên'), ('vang', 'Vàng trở lên'), ('bachkim', 'Bạch Kim trở lên'), ('kimcuong', 'Kim Cương')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='khuyenmai',
            name='so_luong_con',
            field=models.IntegerField(default=9999),
        ),
        migrations.AddField(
            model_name='khuyenmai',
            name='thoi_han_ngay',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterUniqueTogether(
            name='userkhuyenmai',
            unique_together={('nguoi_dung', 'khuyen_mai')},
        ),
    ]
