# Generated by Django 5.1 on 2026-05-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuahang', '0018_khuyenmai_doi_tuong_khuyenmai_so_luong_con_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='khuyenmai',
            name='is_hang_muc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='khuyenmai',
            name='doi_tuong',
            field=models.CharField(choices=[('all', 'Tất cả'), ('bac', 'Bạc trở lên'), ('vang', 'Vàng trở lên'), ('bachkim', 'Bạch Kim trở lên'), ('kimcuong', 'Kim Cương')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='khuyenmai',
            name='thoi_han_ngay',
            field=models.IntegerField(default=30),
        ),
    ]
