# Generated by Django 5.1 on 2026-05-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuahang', '0019_khuyenmai_is_hang_muc_alter_khuyenmai_doi_tuong_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khuyenmai',
            name='is_hang_muc',
        ),
        migrations.AddField(
            model_name='khuyenmai',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='khuyenmai',
            name='doi_tuong',
            field=models.CharField(choices=[('all', 'Tất cả'), ('dong', 'Đồng'), ('bac', 'Bạc'), ('vang', 'Vàng'), ('bachkim', 'Bạch Kim'), ('kimcuong', 'Kim Cương')], default='all', max_length=20),
        ),
    ]
