# Generated by Django 5.1 on 2026-05-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuahang', '0020_remove_khuyenmai_is_hang_muc_khuyenmai_is_vip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='trang_thai',
            field=models.CharField(choices=[('cho_xac_nhan', 'Chờ xác nhận'), ('da_xac_nhan', 'Đã xác nhận'), ('dang_giao', 'Đang giao hàng'), ('da_giao', 'Đã giao hàng'), ('da_huy', 'Đã hủy')], default='cho_xac_nhan', max_length=20),
        ),
    ]
