# Generated by Django 5.1 on 2026-05-23 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuahang', '0021_alter_donhang_trang_thai'),
    ]

    operations = [
        migrations.CreateModel(
            name='YeuCauHoanTien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ly_do', models.CharField(max_length=100)),
                ('mo_ta', models.TextField()),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='hoan_tien/')),
                ('trang_thai', models.CharField(choices=[('cho_xu_ly', 'Chờ xử lý'), ('dang_xu_ly', 'Đang xử lý'), ('da_hoan_tien', 'Đã hoàn tiền'), ('da_tu_choi', 'Từ chối')], default='cho_xu_ly', max_length=20)),
                ('ngay_yeu_cau', models.DateTimeField(auto_now_add=True)),
                ('ngay_xu_ly', models.DateTimeField(blank=True, null=True)),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yeu_cau_hoan_tien', to='cuahang.donhang')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuahang.sanpham')),
            ],
            options={
                'verbose_name': 'Yêu cầu hoàn tiền',
                'verbose_name_plural': 'Yêu cầu hoàn tiền',
                'ordering': ['-ngay_yeu_cau'],
            },
        ),
    ]
