# Generated by Django 5.1 on 2026-05-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuahang', '0022_yeucauhoantien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yeucauhoantien',
            name='mo_ta',
            field=models.TextField(blank=True),
        ),
    ]
