# Generated by Django 5.1 on 2026-05-30 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuahang', '0024_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bangsize',
            options={'verbose_name': 'Bảng size', 'verbose_name_plural': 'Bảng size'},
        ),
        migrations.AlterModelOptions(
            name='chitietdonhang',
            options={'verbose_name': 'Chi tiết đơn hàng', 'verbose_name_plural': 'Chi tiết đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='danhgiasanpham',
            options={'ordering': ['-ngay_danh_gia'], 'verbose_name': 'Đánh giá sản phẩm', 'verbose_name_plural': 'Đánh giá sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='danhmuc',
            options={'verbose_name': 'Danh mục', 'verbose_name_plural': 'Danh mục'},
        ),
        migrations.AlterModelOptions(
            name='donhang',
            options={'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='giohang',
            options={'verbose_name': 'Giỏ hàng', 'verbose_name_plural': 'Giỏ hàng'},
        ),
        migrations.AlterModelOptions(
            name='khuyenmai',
            options={'verbose_name': 'Khuyến mãi / Voucher', 'verbose_name_plural': 'Khuyến mãi / Voucher'},
        ),
        migrations.AlterModelOptions(
            name='nguoidung',
            options={'verbose_name': 'Người dùng', 'verbose_name_plural': 'Người dùng'},
        ),
        migrations.AlterModelOptions(
            name='sanpham',
            options={'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='userkhuyenmai',
            options={'verbose_name': 'Voucher của người dùng', 'verbose_name_plural': 'Voucher của người dùng'},
        ),
        migrations.RemoveField(
            model_name='bangsize',
            name='mo_ta_kich_co',
        ),
        migrations.AlterField(
            model_name='bangsize',
            name='kich_co',
            field=models.CharField(max_length=20, verbose_name='Kích cỡ'),
        ),
        migrations.AlterField(
            model_name='bangsize',
            name='san_pham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bang_size', to='cuahang.sanpham', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_bot',
            field=models.BooleanField(default=False, verbose_name='Là tin nhắn Bot'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(verbose_name='Nội dung tin nhắn'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='ngay_tao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='nguoi_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='chitietdonhang',
            name='don_hang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuahang.donhang', verbose_name='Đơn hàng'),
        ),
        migrations.AlterField(
            model_name='chitietdonhang',
            name='gia',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='chitietdonhang',
            name='san_pham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuahang.sanpham', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='chitietdonhang',
            name='so_luong',
            field=models.IntegerField(verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='danhgiasanpham',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Hình ảnh đánh giá'),
        ),
        migrations.AlterField(
            model_name='danhgiasanpham',
            name='ngay_danh_gia',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày đánh giá'),
        ),
        migrations.AlterField(
            model_name='danhgiasanpham',
            name='nguoi_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá'),
        ),
        migrations.AlterField(
            model_name='danhgiasanpham',
            name='noi_dung',
            field=models.TextField(verbose_name='Nội dung đánh giá'),
        ),
        migrations.AlterField(
            model_name='danhgiasanpham',
            name='san_pham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia', to='cuahang.sanpham', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='danhgiasanpham',
            name='so_sao',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Số sao'),
        ),
        migrations.AlterField(
            model_name='danhmuc',
            name='ten_danh_muc',
            field=models.CharField(max_length=100, verbose_name='Tên danh mục'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='dia_chi_giao',
            field=models.TextField(blank=True, null=True, verbose_name='Địa chỉ giao hàng'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='ho_ten_nhan',
            field=models.CharField(blank=True, max_length=100, verbose_name='Họ tên người nhận'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='ma_giam_gia',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mã giảm giá'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='ngay_dat',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt hàng'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='nguoi_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='so_dien_thoai_nhan',
            field=models.CharField(blank=True, max_length=15, verbose_name='SĐT người nhận'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='tong_tien',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tổng tiền'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='trang_thai',
            field=models.CharField(choices=[('cho_xac_nhan', 'Chờ xác nhận'), ('da_xac_nhan', 'Đã xác nhận'), ('dang_giao', 'Đang giao hàng'), ('da_giao', 'Đã giao hàng'), ('da_huy', 'Đã hủy')], default='cho_xac_nhan', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='giohang',
            name='bien_the',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuahang.sanphambienthe', verbose_name='Biến thể'),
        ),
        migrations.AlterField(
            model_name='giohang',
            name='nguoi_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='giohang',
            name='san_pham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuahang.sanpham', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='giohang',
            name='so_luong',
            field=models.IntegerField(default=1, verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='khuyenmai',
            name='doi_tuong',
            field=models.CharField(choices=[('all', 'Tất cả'), ('dong', 'Đồng'), ('bac', 'Bạc'), ('vang', 'Vàng'), ('bachkim', 'Bạch Kim'), ('kimcuong', 'Kim Cương')], default='all', max_length=20, verbose_name='Đối tượng'),
        ),
        migrations.AlterField(
            model_name='khuyenmai',
            name='gia_tri',
            field=models.IntegerField(verbose_name='Giá trị giảm'),
        ),
        migrations.AlterField(
            model_name='khuyenmai',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='Voucher VIP'),
        ),
        migrations.AlterField(
            model_name='khuyenmai',
            name='loai_giam',
            field=models.CharField(choices=[('phan_tram', 'Giảm phần trăm'), ('tien', 'Giảm số tiền'), ('freeship', 'Freeship')], max_length=20, verbose_name='Loại giảm giá'),
        ),
        migrations.AlterField(
            model_name='khuyenmai',
            name='ma_khuyen_mai',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mã khuyến mãi'),
        ),
        migrations.AlterField(
            model_name='khuyenmai',
            name='mo_ta',
            field=models.TextField(blank=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='khuyenmai',
            name='ngay_bat_dau',
            field=models.DateField(verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='khuyenmai',
            name='ngay_ket_thuc',
            field=models.DateField(verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='khuyenmai',
            name='so_luong_con',
            field=models.IntegerField(default=9999, verbose_name='Số lượng còn lại'),
        ),
        migrations.AlterField(
            model_name='khuyenmai',
            name='ten_khuyen_mai',
            field=models.CharField(max_length=100, verbose_name='Tên khuyến mãi'),
        ),
        migrations.AlterField(
            model_name='khuyenmai',
            name='thoi_han_ngay',
            field=models.IntegerField(default=30, verbose_name='Thời hạn (ngày)'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/macdinh.png', null=True, upload_to='avatars/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='can_nang',
            field=models.FloatField(blank=True, null=True, verbose_name='Cân nặng (kg)'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='chieu_cao',
            field=models.FloatField(blank=True, null=True, verbose_name='Chiều cao (cm)'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='dia_chi',
            field=models.TextField(blank=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email đã xác thực'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='hang_thanh_vien',
            field=models.CharField(choices=[('dong', 'Đồng'), ('bac', 'Bạc'), ('vang', 'Vàng'), ('bachkim', 'Bạch Kim'), ('kimcuong', 'Kim Cương')], default='dong', max_length=20, verbose_name='Hạng thành viên'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='ho_ten',
            field=models.CharField(blank=True, max_length=100, verbose_name='Họ tên'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Mã OTP'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời hạn OTP'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='so_dien_thoai',
            field=models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='so_thich',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sở thích phối đồ'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='chat_lieu',
            field=models.CharField(blank=True, max_length=100, verbose_name='Chất liệu'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='danh_muc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='san_pham', to='cuahang.danhmuc', verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='gioi_tinh',
            field=models.CharField(choices=[('nam', 'Nam'), ('nu', 'Nữ'), ('unisex', 'Unisex')], default='unisex', max_length=20, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='hinh_anh',
            field=models.ImageField(upload_to='sanpham/', verbose_name='Hình ảnh chính'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='loai_san_pham',
            field=models.CharField(choices=[('ao', 'Áo'), ('quan', 'Quần'), ('phu_kien', 'Phụ kiện')], default='ao', max_length=20, verbose_name='Loại sản phẩm'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='mo_ta',
            field=models.TextField(verbose_name='Mô tả sản phẩm'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='phong_cach',
            field=models.CharField(blank=True, max_length=100, verbose_name='Phong cách'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='tags_phoi_do',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tags phối đồ'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='ten_san_pham',
            field=models.CharField(max_length=200, verbose_name='Tên sản phẩm'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='xuat_xu',
            field=models.CharField(default='Việt Nam', max_length=100, verbose_name='Xuất xứ'),
        ),
        migrations.AlterField(
            model_name='sanphambienthe',
            name='gia',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='sanphambienthe',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='sanpham/bienthe/', verbose_name='Hình ảnh biến thể'),
        ),
        migrations.AlterField(
            model_name='sanphambienthe',
            name='kich_co',
            field=models.CharField(max_length=20, verbose_name='Kích cỡ'),
        ),
        migrations.AlterField(
            model_name='sanphambienthe',
            name='mau_sac',
            field=models.CharField(max_length=50, verbose_name='Màu sắc'),
        ),
        migrations.AlterField(
            model_name='sanphambienthe',
            name='san_pham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bien_the', to='cuahang.sanpham', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='sanphambienthe',
            name='so_luong',
            field=models.IntegerField(default=10, verbose_name='Số lượng tồn'),
        ),
        migrations.AlterField(
            model_name='userkhuyenmai',
            name='da_su_dung',
            field=models.BooleanField(default=False, verbose_name='Đã sử dụng'),
        ),
        migrations.AlterField(
            model_name='userkhuyenmai',
            name='khuyen_mai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuahang.khuyenmai', verbose_name='Khuyến mãi'),
        ),
        migrations.AlterField(
            model_name='userkhuyenmai',
            name='ngay_nhan',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày nhận'),
        ),
        migrations.AlterField(
            model_name='userkhuyenmai',
            name='ngay_su_dung',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày sử dụng'),
        ),
        migrations.AlterField(
            model_name='userkhuyenmai',
            name='nguoi_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='yeucauhoantien',
            name='don_hang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yeu_cau_hoan_tien', to='cuahang.donhang', verbose_name='Đơn hàng'),
        ),
        migrations.AlterField(
            model_name='yeucauhoantien',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='hoan_tien/', verbose_name='Hình ảnh minh chứng'),
        ),
        migrations.AlterField(
            model_name='yeucauhoantien',
            name='ly_do',
            field=models.CharField(max_length=100, verbose_name='Lý do'),
        ),
        migrations.AlterField(
            model_name='yeucauhoantien',
            name='mo_ta',
            field=models.TextField(blank=True, verbose_name='Mô tả chi tiết'),
        ),
        migrations.AlterField(
            model_name='yeucauhoantien',
            name='ngay_xu_ly',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày xử lý'),
        ),
        migrations.AlterField(
            model_name='yeucauhoantien',
            name='ngay_yeu_cau',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày yêu cầu'),
        ),
        migrations.AlterField(
            model_name='yeucauhoantien',
            name='nguoi_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='yeucauhoantien',
            name='san_pham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuahang.sanpham', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='yeucauhoantien',
            name='trang_thai',
            field=models.CharField(choices=[('cho_xu_ly', 'Chờ xử lý'), ('dang_xu_ly', 'Đang xử lý'), ('da_hoan_tien', 'Đã hoàn tiền'), ('da_tu_choi', 'Từ chối')], default='cho_xu_ly', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
