# Generated by Django 5.1 on 2026-05-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuahang', '0025_alter_bangsize_options_alter_chitietdonhang_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(help_text='Hỗ trợ emoji và tiếng Việt', verbose_name='Nội dung tin nhắn'),
        ),
        migrations.AlterModelTable(
            name='chatmessage',
            table='chatmessage',
        ),
    ]
