# Generated by Django 5.1 on 2026-05-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuahang', '0026_alter_chatmessage_message_alter_chatmessage_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='danhmuc',
            name='gioi_tinh_hop_le',
            field=models.CharField(choices=[('nam', 'Nam'), ('nu', 'Nữ'), ('unisex', 'Unisex')], default='all', max_length=50, verbose_name='Áp dụng cho giới tính'),
        ),
    ]
