# Generated by Django 5.1 on 2026-05-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuahang', '0027_danhmuc_gioi_tinh_hop_le'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='danhmuc',
            options={'ordering': ['ten_danh_muc'], 'verbose_name': 'Danh mục', 'verbose_name_plural': 'Danh mục'},
        ),
        migrations.AlterField(
            model_name='danhmuc',
            name='gioi_tinh_hop_le',
            field=models.CharField(choices=[('nam', 'Nam'), ('nu', 'Nữ'), ('unisex', 'Unisex')], default='unisex', max_length=20, verbose_name='Áp dụng cho giới tính'),
        ),
    ]
