"""
Django settings for thoitrang project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
AUTH_USER_MODEL = 'cuahang.NguoiDung'
# Trong settings.py (thêm/sửa phần này)
LOGIN_URL = '/dang-nhap/'
LOGIN_REDIRECT_URL = '/'          # Sau khi login sẽ về trang chủ
LOGOUT_REDIRECT_URL = '/'         # Sau khi logout về trang chủ


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-114ck$uo5pqz6lct0hr9xd^hgs6r@8xnb2u(r9e^cg60h(s+ka'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cuahang',
    'django_bootstrap5' ,
    'crispy_forms',
    'import_export',
    
]

CRISPY_TEMPLATE_PACK = 'bootstrap5'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'thoitrang.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cuahang.context_processors.menu_categories',
            ],
        },
    },
]

WSGI_APPLICATION = 'thoitrang.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'thoitrang_db',
        'USER': 'root',
        'PASSWORD': 'duongvo19-12',          # thay bằng password MySQL của bạn
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',        # ← Quan trọng
        },
        'TEST': {
            'CHARSET': 'utf8mb4',
            'COLLATION': 'utf8mb4_unicode_ci',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'vi'
TIME_ZONE = 'Asia/Ho_Chi_Minh'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ====================== EMAIL CONFIGURATION (Gmail thật) ======================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Thay bằng thông tin Gmail của bạn
EMAIL_HOST_USER = 'kiet22082006071@vnkgu.edu.vn'          # Email gửi OTP
EMAIL_HOST_PASSWORD = 'qaht dgyi dntv emmx'                       # ← Hiện tại là mật khẩu gốc

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# ====================== JAZZMIN ADMIN CONFIG (NÂNG CẤP ĐẸP) ======================
JAZZMIN_SETTINGS = {
    # Tiêu đề và Logo
    "site_title": "OutfitLab Admin",
    "site_header": "OutfitLab",
    "site_brand": "OutfitLab",
    "site_logo": "images/logo.png",
    "login_logo": "images/logo.png",
    "login_logo_dark": "images/logo.png",

    # Custom JS
    "custom_js": "js/admin.js",

    # Màu sắc chủ đạo (Đồng bộ với website)
    "theme": "default",
    "skin": "skin-pink",
    "primary_color": "#ec4899",      # Hồng chủ đạo
    "accent_color": "#0ea5e9",       # Xanh dương

    # Welcome & Branding
    "welcome_sign": "Chào mừng đến với OutfitLab Admin",
    "copyright": "© 2026 OutfitLab - Thời Trang Việt Nam",

    # Top menu
    "topmenu_links": [
    # Link vào Django Admin chính
    {"name": "🔧 Quản Trị Hệ Thống", "url": "/admin/", "new_window": False},
    
    # Link vào Dashboard tùy chỉnh
    {"name": "📊 Bảng Điều Khiển", "url": "/admin-dashboard/", "new_window": False, "icon": "fas fa-chart-bar"},
    
    # Các link khác nếu có
    {"name": "🏠 Trang Chủ", "url": "/", "new_window": True},
],

    # Icons cho tất cả các Model (đã cập nhật đầy đủ)
    "icons": {
        "auth.User": "fas fa-user",
        "cuahang.NguoiDung": "fas fa-users-cog",
        "cuahang.DanhMuc": "fas fa-tags",
        "cuahang.SanPham": "fas fa-shirt",
        "cuahang.SanPhamBienThe": "fas fa-palette",
        "cuahang.DanhGiaSanPham": "fas fa-star",
        "cuahang.BangSize": "fas fa-ruler-combined",
        "cuahang.GioHang": "fas fa-shopping-cart",
        "cuahang.DonHang": "fas fa-receipt",
        "cuahang.ChiTietDonHang": "fas fa-list-ul",
        "cuahang.KhuyenMai": "fas fa-gift",
        "cuahang.UserKhuyenMai": "fas fa-ticket-alt",
        "cuahang.YeuCauHoanTien": "fas fa-undo-alt",
        "cuahang.ChatMessage": "fas fa-comments",
    },

    # Cấu hình UI & Animation
    "show_ui_builder": True,
    "changeform_format": "horizontal_tabs",
    "theme": "cyborg",
    "default_theme_mode": "light",
    "related_modal_active": True,
    "use_google_fonts_cdn": True,
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # Order of models in sidebar
    "order_with_respect_to": [
        "cuahang.NguoiDung",
        "cuahang.SanPham",
        "cuahang.SanPhamBienThe",
        "cuahang.DanhMuc",
        "cuahang.DonHang",
        "cuahang.YeuCauHoanTien",
        "cuahang.KhuyenMai",
    ],

    # Custom link
    "usermenu_links": [
        {"name": "Xem Website", "url": "/", "new_window": True, "icon": "fas fa-globe"},
    ],
}

# ====================== JAZZMIN UI TWEAKS ======================
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    
    "brand_colour": "navbar-pink",
    "accent": "accent-pink",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "footer_fixed": False,
    "sidebar_fixed": True,
    
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    
    "theme": "cyborg",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": True,
}